global:
  resolve_timeout: 5m
  smtp_from: 'alerts@schoolsas.andrew-nzioki.com'
  smtp_smarthost: 'smtp.resend.com:587'
  smtp_auth_username: 'resend'
  smtp_auth_password: 're_9UYw66fw_Njxk8oHV58CTFkoBbDcsuPou'
  smtp_require_tls: true
  smtp_hello: 'alertmanager.example.org'


route:
  group_by: ['alertname', 'job', 'severity', 'instance', 'timestamp']
  group_wait: 0s                # Wait minimally before sending a notification
  group_interval: 5s            # Send notifications for changes to alerts every 5s
  repeat_interval: 5s           # Repeat notifications every 5s
  receiver: 'email-notifications'
  routes:
  - match:
      severity: critical
    receiver: 'pager-duty-critical'
    repeat_interval: 5s         # Changed from 4h
  - match_re:
      severity: ^(warning|info)$
    receiver: 'email-notifications'
    repeat_interval: 5s         # Changed from 12h

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'nziokiofficial@gmail.com'
    send_resolved: true
    html: '{{ template "email.default.html" . }}'
    headers:
      subject: '{{ template "email.default.subject" . }}'

- name: 'pager-duty-critical'
  webhook_configs:
  - url: 'http://pagerduty-webhook:8080/'
    send_resolved: true

- name: 'slack-notifications'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX'
    channel: '#alerts'
    send_resolved: true
    icon_emoji: ':warning:'
    title: '{{ template "slack.default.title" . }}'
    text: '{{ template "slack.default.text" . }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']