global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Consul service discovery for all services
  - job_name: "consul-services"
    consul_sd_configs:
      - server: "consul:8500"
        services: []  # Empty list means "all services"
    relabel_configs:
      # Add service name as a label
      - source_labels: [__meta_consul_service]
        target_label: service
      # Use consul service name as the instance label
      - source_labels: [__meta_consul_service_id]
        target_label: instance
      # Get metrics endpoint from consul service metadata
      - source_labels: [__meta_consul_service_metadata_metrics_path]
        regex: (.+)
        target_label: __metrics_path__
        replacement: $1
      # Default metrics endpoint if not specified
      - source_labels: [__meta_consul_service_metadata_metrics_path]
        regex: ""
        target_label: __metrics_path__
        replacement: /metrics

  # Node Exporter for host metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]


  - job_name: "backend-api"
    scrape_interval: 5s
    static_configs:
      - targets: ["backend-api:8080"] # backend-api service
      
    metrics_path: /metrics