server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag
            time: time

      - regex:
          expression: (?P<container_name>(?:[^|]*[^|]))
          source: tag
      
      - regex:
          expression: (?P<app_name>(?:[^_]*[^_]))
          source: container_name

      - timestamp:
          source: time
          format: RFC3339Nano

      - labels:
          stream:
          container_name:
          app_name:

      # Extract log level for structured logs
      - json:
          expressions:
            level: level
            message: message

      - labels:
          level:

  # Special configuration for FastAPI logs
  - job_name: fastapi
    static_configs:
      - targets:
          - localhost
        labels:
          job: fastapi
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag

      - regex:
          expression: (?P<container_name>fastapi.*)
          source: tag

      - match:
          selector: '{container_name=~"fastapi.*"}'
          stages:
            - json:
                expressions:
                  log: log
            - json:
                expressions:
                  level: level
                  message: message
                  timestamp: timestamp
                  request_id: request_id
                  method: method
                  url: url
                  status_code: status_code
                source: log

            - labels:
                level:
                request_id:
                method:
                status_code: